### ISSUE TITLE
norm on complex Grassman is not Real on Julia nightly

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaNLSolvers/Manifolds.jl#87] opened 2020-01-04 18:31 UTC
Like here: https://ci.appveyor.com/project/pkofod/manifolds-jl/builds/29893976/job/nwfl88incvx5pawh

**Comment by sethaxen** [comment] 2020-01-04 19:43
I noticed that. I couldn't reproduce it on my machine. It doesn't make any sense to me, since `Grassmann` doesn't overload `norm`, and the default implementation in ManifoldsBase calls `real`. Let's keep an eye on it and see if it sorts itself out (i.e. is a bug in Julia). If anyone can reproduce it on nightly, let me know.

**Comment by sethaxen** [comment] 2020-01-23 07:27
This appears to now be fixed on the nightlies. The last failing build with this error that I could find was https://travis-ci.org/JuliaNLSolvers/Manifolds.jl/jobs/638410949. The first passing build was https://travis-ci.org/JuliaNLSolvers/Manifolds.jl/jobs/638540492. The diff on julia nightly over those two builds was https://github.com/JuliaLang/julia/compare/a7cd97a...4254045. I can't see anything in the diff that would have fixed this, but it does seem to be fixed.

**Closed by sethaxen** 2020-01-23 07:27 UTC
